"""empty message

Revision ID: d4fb0dfb9763
Revises: e8a4f2ddd087
Create Date: 2021-08-04 16:11:17.278499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fb0dfb9763'
down_revision = 'e8a4f2ddd087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_exp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_exp')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
